Add alpine versions of images.
drupal-docker/php pull request #50
Opened 2016-09-13 11:24 UTC by slashrsm

Image size 27MB vs 150MB.

2016-09-13 12:56 UTC, zaporylie commented
Failing due to missing alpine for 5.4 and missing `apt-get`. You may want to use `apk` instead

2016-09-13 21:14 UTC, slashrsm commented
Green.

2016-09-20 19:29 UTC, zaporylie commented on 5.6-alpine/fpm/Dockerfile
> +   && apk add --no-cache sudo git libpng libjpeg libpq \
I don't think we need git or sudo for *-fpm images (5.6, 7.0, 7.1).

2016-09-20 19:34 UTC, zaporylie requested changes
I think it's almost good to go. Just small issue I've mentioned above - *-fpm images should be free sudo or git.

2016-09-20 19:37 UTC, zaporylie commented
Oh... comment was actually added below 😄  still learning how to use new Github review tools.

2016-09-23 09:42 UTC, slashrsm commented on 5.6-alpine/fpm/Dockerfile
> +   && apk add --no-cache sudo git libpng libjpeg libpq \
Makes sense. Done.

2016-09-23 11:08 UTC, slashrsm commented
Test fails seems to be unrelated since they happened in PHP 5.4 image, which we didn't touch here.

2016-09-23 11:17 UTC, zaporylie commented
I have restarted that job. Feel like it's Travis infra issue.

Anyway - this stats looks impressive:
7.1-alpine          latest              bfaabef70542        Less than a second ago   96.38 MB
7.1-alpine/fpm      latest              ea039aa6c4dc        Less than a second ago   89.67 MB
7.1                 latest              75cc51bad7d0        Less than a second ago   434.7 MB
7.1/fpm             latest              3f0f00c4af23        Less than a second ago   408.9 MB

2016-09-23 15:11 UTC, slashrsm commented
Agreed! 
What can we do regarding Travis? Wait?

2016-09-23 17:42 UTC, zaporylie commented
Just got alert from Docker Hub that 5.4-cli is failing there too. I will investigate later this weekend what could cause that error.

2016-09-26 06:33 UTC, zaporylie approved these changes

2016-09-26 06:35 UTC, zaporylie commented
Ok, so "wait" was enough :) Just rerun failing build and now it's ok :) I'm gonna prepare tags on hub.docker.com and merge that pull request as soon as it's done.

2016-09-26 06:58 UTC, merged

2016-09-26 09:42 UTC, slashrsm commented
Yay! Thanks @zaporylie.